# Copyright (c) 2021 Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
# 
title: "Deploy a WordPress instance on OCI"
description: ${Messages.solutionsHub.solutions.wordpress.longDescription()}
schemaVersion: 1.1.0
version: "20190304"
locale: "en"

variableGroups:
- title: ${Messages.solutionsHub.generalConfig()}
  visible: false
  variables:
  - tenancy_ocid
  - region
  - instance_os
  - linux_os_version
  - label_prefix

- title: ${Messages.solutionsHub.solutions.wordpress.variableGroups.wordPressConfigurationTitle()}
  visible: true  
  variables:
    - wp_admin_user
    - wp_admin_password
    - show_advanced

- title: ${Messages.solutionsHub.solutions.wordpress.variableGroups.mySqlConfigurationTitle()}
  visible: 
      and:
        - show_advanced  
  variables:
    - wp_db_user
    - wp_schema



- title: ${Messages.solutionsHub.solutions.wordpress.variableGroups.instanceConfigurationTitle()}
  visible: 
      and:
        - show_advanced
  variables:
    - compartment_ocid
    - availability_domain_name 
    - instance_shape
    - instance_ocpus
    - instance_shape_config_memory_in_gbs
    - generate_public_ssh_key
    - public_ssh_key


- title: ${Messages.solutionsHub.solutions.wordpress.variableGroups.networkConfigurationTitle()}
  visible: 
      and:
        - show_advanced
  variables:
     - vcn
     - vcn_cidr

outputGroups:
- title: ${Messages.solutionsHub.solutions.wordpress.outputGroups.serviceEndpointsTitle()}
  outputs:
    - wordpress_public_ip
    - wordpress_admin_url
- title: ${Messages.solutionsHub.solutions.wordpress.outputGroups.generatedPasswordsTitle()}
  outputs:
    - generated_ssh_private_key

outputs:
  wordpress_public_ip:
    type: link
    title: ${Messages.solutionsHub.solutions.wordpress.outputs.wordpressPublicIpTitle()}
    description: ${Messages.solutionsHub.solutions.wordpress.outputs.wordpressPublicIpDescription()}
  wordpress_admin_url:
    type: link
    title: ${Messages.solutionsHub.solutions.wordpress.outputs.wordpressAdminUrlTitle()}
    description: ${Messages.solutionsHub.solutions.wordpress.outputs.wordpressAdminUrlDescription()}
  generated_ssh_private_key:
    title: ${Messages.solutionsHub.solutions.wordpress.outputs.generatedSshPrivateKeyTitle()}
    description: ${Messages.solutionsHub.solutions.wordpress.outputs.generatedSshPrivateKeyDescription()}
    type: copyableString
    visible: true

primaryOutputButton: wordpress_admin_url

variables:

  show_advanced:
    type: boolean
    title:  ${Messages.solutionsHub.solutions.wordpress.variables.showAdvancedTitle()}
    description:  ${Messages.solutionsHub.solutions.wordpress.variables.showAdvancedDescription()}
    visible: false
    default: false

# MySQL

  wp_db_user:
    type: string
    required: false
    title: ${Messages.solutionsHub.solutions.wordpress.variables.wpDbUserTitle()}
    description: ${Messages.solutionsHub.solutions.wordpress.variables.wpDbUserDescription()}
    minLength: 2
    maxLength: 14
    pattern: "^[a-zA-Z][a-zA-Z0-9]+$"
    visible: 
      and:
        - show_advanced

  wp_schema:
    type: string
    required: false
    title: ${Messages.solutionsHub.solutions.wordpress.variables.wpSchemaTitle()}
    description: ${Messages.solutionsHub.solutions.wordpress.variables.wpSchemaDescription()}
    visible: 
      and:
        - show_advanced
  
  wp_admin_user:
    type: string
    required: true
    title: ${Messages.solutionsHub.solutions.wordpress.variables.wpAdminUserTitle()}
    description: ${Messages.solutionsHub.solutions.wordpress.variables.wpAdminUserDescription()}
    minLength: 2
    maxLength: 14
    pattern: "^[a-zA-Z][a-zA-Z0-9]+$"
    visible: true

  wp_admin_password:
    type: password
    required: true
    title: ${Messages.solutionsHub.solutions.wordpress.variables.wpAdminPasswordTitle()}
    description: ${Messages.solutionsHub.solutions.wordpress.variables.wpAdminPasswordDescription()}
    #pattern: "^(?=[a-zA-Z0-9!@#%^*_+\-:?.,\[\]\{\}]{8,32}$)(?=.*?[a-z])(?=.*?[A-Z])(?=.*?[0-9]).*"
    pattern: "^(?=.*[!@#%^*_+\\-:?.,\\[\\]\\{\\}])(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?!.*[$\\(\\)]).{8,32}$"
  
# Network
  vcn:
    type: string
    visible: 
      and:
        - show_advanced
    required: true
    title: ${Messages.solutionsHub.solutions.wordpress.variables.vcnTitle()}
    description: ${Messages.solutionsHub.solutions.wordpress.variables.vcnDescription()}

  vcn_cidr:
    type: string
    visible: 
      and:
        - show_advanced
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: ${Messages.solutionsHub.solutions.wordpress.variables.vcnCidrTitle()}
    description: ${Messages.solutionsHub.solutions.wordpress.variables.vcnCidrDescription()}

# Instance 
  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    visible: 
      and:
        - show_advanced
    title: ${Messages.solutionsHub.solutions.wordpress.variables.compartmentOcidTitle()}
    description: ${Messages.solutionsHub.solutions.wordpress.variables.compartmentOcidDescription()}

  availability_domain_name:
    type: oci:identity:availabilitydomain:name
    required: true
    visible: 
      and:
        - show_advanced
    title: ${Messages.solutionsHub.solutions.wordpress.variables.availabilityDomainNameTitle()}
    description: ${Messages.solutionsHub.solutions.wordpress.variables.availabilityDomainNameDescription()}
    dependsOn:
      regionName: ${region}
      compartmentId: ${compartment_ocid}

  instance_shape:
    type: oci:core:instanceshape:name
    required: false
    visible: 
      and:
        - show_advanced
    title: ${Messages.solutionsHub.solutions.wordpress.variables.instanceShapeTitle()}
    description: ${Messages.solutionsHub.solutions.wordpress.variables.instanceShapeDescription()}
    default: "VM.Standard.E2.1.Micro"
    dependsOn:
      compartmentId: ${compartment_ocid}
  
  instance_ocpus:
    type: integer
    minimum: 1
    maximum: 64
    title: ${Messages.solutionsHub.solutions.wordpress.variables.instanceOcpusTitle()}
    description: ${Messages.solutionsHub.solutions.wordpress.variables.instanceOcpusDescription()}
    visible:
      and:
        - show_advanced
        - or:
          - eq:
            - instance_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - instance_shape 
            - "VM.Standard.E4.Flex"

  instance_shape_config_memory_in_gbs:
    type: integer
    minimum: 1
    maximum: 1024
    title: ${Messages.solutionsHub.solutions.wordpress.variables.instanceShapeConfigMemoryInGbsTitle()}
    description: ${Messages.solutionsHub.solutions.wordpress.variables.instanceShapeConfigMemoryInGbsDescription()}
    visible:
      and:
        - show_advanced
        - or:
          - eq:
            - instance_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - instance_shape 
            - "VM.Standard.E4.Flex"

  instance_os:
    type: enum
    required: false
    visible: 
      and:
        - show_advanced
    title: ${Messages.solutionsHub.solutions.wordpress.variables.instanceOsTitle()}
    description: ${Messages.solutionsHub.solutions.wordpress.variables.instanceOsDescription()}
    default: "Oracle Linux"
    enum:
      - "Oracle Linux"

  linux_os_version:
    type: enum
    required: false
    visible: 
      and:
        - show_advanced
    title: ${Messages.solutionsHub.solutions.wordpress.variables.linuxOsVersionTitle()}
    description: ${Messages.solutionsHub.solutions.wordpress.variables.linuxOsVersionDescription()}
    default: "7.8"
    enum:
      - "7.8"

  label_prefix:
    type: string
    required: false
    visible: false
    title: ${Messages.solutionsHub.solutions.wordpress.variables.labelPrefixTitle()}
    description: ${Messages.solutionsHub.solutions.wordpress.variables.labelPrefixDescription()}

  

  generate_public_ssh_key:
    type: boolean
    title: ${Messages.solutionsHub.solutions.wordpress.variables.generatePublicSshKeyTitle()}
    required: true
    visible: #($show_advanced  == ""Yes"")
      and:
        - show_advanced 

  public_ssh_key:
    type: oci:core:ssh:publickey
    title: ${Messages.solutionsHub.solutions.wordpress.variables.publicSshKeyTitle()}
    additionalProps:
      allowMultiple: true
    description: ${Messages.solutionsHub.solutions.wordpress.variables.publicSshKeyDescription()}
    required: false
    pattern: "((^(ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)(,((ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)*$"
    visible: 
      and:
        - show_advanced
        - not:
          - generate_public_ssh_key

